# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0e519839a8f38959460b2c3325fc2c6e50f981d4be3b549b3be257e1effbb64862cffb26cd99b0b489c8fd404fff62b96329fb87e6780710d65f20c08477f60

test:
  secret_key_base: c430ee0d1f0b05dd9cd9a32e366e9aa49561836a6c38fce8c1a4e0f9a286af4dd02ab0d3c1e56a91d5f9e72c0eed2ee183bb9569ccdf3a260ac893107ce0371e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
